#index:
#    path: /
#    controller: App\Controller\DefaultController::index
blogger_blog_replyCommentaire:
  path:    /replycomment/{id}/{comment_id}/{user}
  defaults: {_controller: BloggerBlogBundle:Comment:replyComment }
  requirements:
    id:  \d+
    comment_id:  \d+
    user:  \d+
