<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpPGk8K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpPGk8K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpPGk8K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpPGk8K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHpPGk8K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HpPGk8K',
    'container.build_id' => '31c19322',
    'container.build_time' => 1649932630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpPGk8K');
